Header header

uint8   LT_NORMAL         = 0
uint8   LT_ENTRY          = 1
uint8   LT_EXIT           = 2
uint8   LT_CONNECT        = 3
uint8   LT_EMERGENCY      = 4
uint8   LT_STOP           = 5
uint8   LT_EMERGENCY_STOP = 6
uint8   LT_ACCELERATE     = 7
uint8   LT_DECELERATE     = 8
uint8   LT_AVOID_DANGER   = 9
uint8   LT_INTERSECTION   = 10
uint8   LT_TOLL_GATE      = 11
uint8   LT_CHECK_POINT    = 12
uint8   LT_TURN_AROUND    = 13
uint8   LT_FORMING        = 14      #A Lane may appear at junction
uint8   LT_DESTORY        = 15      #A Lane may disapper at junction
uint8   LT_RAMP           = 16