// Generated by gencpp from file perception_msgs/brake_info.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_BRAKE_INFO_H
#define PERCEPTION_MSGS_MESSAGE_BRAKE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct brake_info_
{
  typedef brake_info_<ContainerAllocator> Type;

  brake_info_()
    : header()
    , automode_status(false)
    , brake_pedal_status(false)
    , mastercy_linder_press(0.0)  {
    }
  brake_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , automode_status(false)
    , brake_pedal_status(false)
    , mastercy_linder_press(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _automode_status_type;
  _automode_status_type automode_status;

   typedef uint8_t _brake_pedal_status_type;
  _brake_pedal_status_type brake_pedal_status;

   typedef double _mastercy_linder_press_type;
  _mastercy_linder_press_type mastercy_linder_press;





  typedef boost::shared_ptr< ::perception_msgs::brake_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::brake_info_<ContainerAllocator> const> ConstPtr;

}; // struct brake_info_

typedef ::perception_msgs::brake_info_<std::allocator<void> > brake_info;

typedef boost::shared_ptr< ::perception_msgs::brake_info > brake_infoPtr;
typedef boost::shared_ptr< ::perception_msgs::brake_info const> brake_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::brake_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::brake_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::brake_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::brake_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::brake_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::brake_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::brake_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::brake_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::brake_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "133e8cf67675f580e17b040db3d7058d";
  }

  static const char* value(const ::perception_msgs::brake_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x133e8cf67675f580ULL;
  static const uint64_t static_value2 = 0xe17b040db3d7058dULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::brake_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/brake_info";
  }

  static const char* value(const ::perception_msgs::brake_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::brake_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool automode_status  #    // true, automode turn on;\n\
bool brake_pedal_status  #    // true, turn on;\n\
float64 mastercy_linder_press #\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::brake_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::brake_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.automode_status);
      stream.next(m.brake_pedal_status);
      stream.next(m.mastercy_linder_press);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct brake_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::brake_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::brake_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "automode_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.automode_status);
    s << indent << "brake_pedal_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_pedal_status);
    s << indent << "mastercy_linder_press: ";
    Printer<double>::stream(s, indent + "  ", v.mastercy_linder_press);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_BRAKE_INFO_H
