// Generated by gencpp from file perception_msgs/inspva_info.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_INSPVA_INFO_H
#define PERCEPTION_MSGS_MESSAGE_INSPVA_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct inspva_info_
{
  typedef inspva_info_<ContainerAllocator> Type;

  inspva_info_()
    : header()
    , time_stamp(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , vehicle_x(0.0)
    , vehicle_y(0.0)
    , vehicle_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , azimuth_rate(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , valid(false)  {
    }
  inspva_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_stamp(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , vehicle_x(0.0)
    , vehicle_y(0.0)
    , vehicle_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , azimuth_rate(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;

   typedef double _vehicle_x_type;
  _vehicle_x_type vehicle_x;

   typedef double _vehicle_y_type;
  _vehicle_y_type vehicle_y;

   typedef double _vehicle_z_type;
  _vehicle_z_type vehicle_z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef double _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef double _azimuth_rate_type;
  _azimuth_rate_type azimuth_rate;

   typedef double _acc_x_type;
  _acc_x_type acc_x;

   typedef double _acc_y_type;
  _acc_y_type acc_y;

   typedef double _acc_z_type;
  _acc_z_type acc_z;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::perception_msgs::inspva_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::inspva_info_<ContainerAllocator> const> ConstPtr;

}; // struct inspva_info_

typedef ::perception_msgs::inspva_info_<std::allocator<void> > inspva_info;

typedef boost::shared_ptr< ::perception_msgs::inspva_info > inspva_infoPtr;
typedef boost::shared_ptr< ::perception_msgs::inspva_info const> inspva_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::inspva_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::inspva_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::inspva_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::inspva_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::inspva_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::inspva_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::inspva_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::inspva_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::inspva_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37de5e5440508bfc95b9039ab41d4f7d";
  }

  static const char* value(const ::perception_msgs::inspva_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37de5e5440508bfcULL;
  static const uint64_t static_value2 = 0x95b9039ab41d4f7dULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::inspva_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/inspva_info";
  }

  static const char* value(const ::perception_msgs::inspva_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::inspva_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 time_stamp\n\
\n\
float64 latitude \n\
float64 longitude\n\
float64 height\n\
float64 vehicle_x\n\
float64 vehicle_y\n\
float64 vehicle_z\n\
float64 roll\n\
float64 pitch\n\
float64 azimuth\n\
float64 roll_rate\n\
float64 pitch_rate \n\
float64 azimuth_rate\n\
float64 acc_x\n\
float64 acc_y\n\
float64 acc_z\n\
bool valid\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::inspva_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::inspva_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_stamp);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.vehicle_x);
      stream.next(m.vehicle_y);
      stream.next(m.vehicle_z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.azimuth);
      stream.next(m.roll_rate);
      stream.next(m.pitch_rate);
      stream.next(m.azimuth_rate);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inspva_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::inspva_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::inspva_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_stamp: ";
    Printer<double>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "vehicle_x: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_x);
    s << indent << "vehicle_y: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_y);
    s << indent << "vehicle_z: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "roll_rate: ";
    Printer<double>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "pitch_rate: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "azimuth_rate: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_rate);
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_INSPVA_INFO_H
