// Generated by gencpp from file perception_msgs/kouliang.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_KOULIANG_H
#define PERCEPTION_MSGS_MESSAGE_KOULIANG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_msgs/objects.h>
#include <perception_msgs/road_info.h>
#include <perception_msgs/vehicle_info.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct kouliang_
{
  typedef kouliang_<ContainerAllocator> Type;

  kouliang_()
    : header()
    , k_objects()
    , k_road_info()
    , k_vehicle_info()  {
    }
  kouliang_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , k_objects(_alloc)
    , k_road_info(_alloc)
    , k_vehicle_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::perception_msgs::objects_<ContainerAllocator>  _k_objects_type;
  _k_objects_type k_objects;

   typedef  ::perception_msgs::road_info_<ContainerAllocator>  _k_road_info_type;
  _k_road_info_type k_road_info;

   typedef  ::perception_msgs::vehicle_info_<ContainerAllocator>  _k_vehicle_info_type;
  _k_vehicle_info_type k_vehicle_info;





  typedef boost::shared_ptr< ::perception_msgs::kouliang_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::kouliang_<ContainerAllocator> const> ConstPtr;

}; // struct kouliang_

typedef ::perception_msgs::kouliang_<std::allocator<void> > kouliang;

typedef boost::shared_ptr< ::perception_msgs::kouliang > kouliangPtr;
typedef boost::shared_ptr< ::perception_msgs::kouliang const> kouliangConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::kouliang_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::kouliang_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::kouliang_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::kouliang_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::kouliang_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::kouliang_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::kouliang_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::kouliang_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::kouliang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c746336ebf402ec7bde66d961a7e9b60";
  }

  static const char* value(const ::perception_msgs::kouliang_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc746336ebf402ec7ULL;
  static const uint64_t static_value2 = 0xbde66d961a7e9b60ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::kouliang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/kouliang";
  }

  static const char* value(const ::perception_msgs::kouliang_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::kouliang_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
objects k_objects\n\
road_info k_road_info\n\
vehicle_info k_vehicle_info\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: perception_msgs/objects\n\
Header header\n\
uint64 sys_time_us              #/*用于各传感器消息时间同步的时间戳*/\n\
object_info[] objects\n\
================================================================================\n\
MSG: perception_msgs/object_info\n\
Header header\n\
int32 obj_id            #/*!< 目标编号 */\n\
uint8 type              #/*!< 类型: perception ObjectType */\n\
\n\
float64 x_v             #/*!< 纵向距离(米) */\n\
float64 heading_c       #/*!< 中心点heading角(弧度单位) */\n\
float64 heading_l       #/*!< 左侧端点heading角, 相机(弧度单位) */\n\
float64 heading_r       #/*!< 右侧端点heading角, 相机(弧度单位) */\n\
float64 heading_speed   #/*!< 运行的速度方向(弧度单位) */\n\
float64 speed           #/*!< 速度, 雷达(米/秒) */\n\
\n\
int32 sensor_type		#/* !< 0: camera; 1: radar; 2: fused */\n\
\n\
##/*! 注意：当只有雷达检测出来的时候都设置为100米，宽度为-100米*/\n\
float64 height          #/* !< object 高度(米) */\n\
float64 width           #/* !< object 宽度(米) */\n\
float64 length          #/* !< object 长度(米) */\n\
bool is_top_surface     #/* !< 是否为车辆的上表面，相对x轴方向 */\n\
\n\
int32 image_x   \n\
int32 image_y\n\
int32 image_w\n\
int32 image_h\n\
\n\
float64 prob            #/* !< object 置信度0-1 */\n\
\n\
================================================================================\n\
MSG: perception_msgs/road_info\n\
Header header\n\
uint64 sys_time_us              #/*用于各传感器消息时间同步的时间戳*/\n\
lane_info[] vlanes              #/*存储车道信息*/\n\
lane_mark_info[] vlane_marks    #/*存储车道线信息*/\n\
float64 lane_departure_angle     #/*!< 道路与车身坐标系的夹角(弧度单位[-PI,PI]) */\n\
float64 lane_departure_distance  # /*!< 自车与车道中心线的距离 */\n\
================================================================================\n\
MSG: perception_msgs/lane_info\n\
Header header\n\
uint32[] vleft_mark_index\n\
uint32[] vright_mark_index\n\
float64[] speed_limit\n\
int32 lane_id                # /*< 车道线编号 当前车道是0，从左至右： - 2, -1, 0， 1, 2 */\n\
int32 lane_hd_id             # 高精地图对应的车道id \n\
\n\
================================================================================\n\
MSG: perception_msgs/lane_mark_info\n\
Header header\n\
uint8 mark_type      #/*!< 类型 LaneMarkingType*/\n\
uint8 mark_color     #/*!< 类型 LaneMarkingColor */\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d            # /* y = a * pow(x,3) + b * pow(x,2) + c * x + d */\n\
float64 x_start      # /*!< 纵向起始点(米) */\n\
float64 x_end        # /*!< 纵向终止点(米) */\n\
\n\
float64 image_a\n\
float64 image_b\n\
float64 image_c\n\
float64 image_d\n\
float64 image_x_start\n\
float64 image_x_end\n\
\n\
================================================================================\n\
MSG: perception_msgs/vehicle_info\n\
Header header\n\
float64 heading_lane   #/*!< 当前车道与Host车辆坐标系x轴夹角,绕x轴旋转，弧度单位,取值范围：(0 – 2π) */\n\
float64 dist_to_line   #/*!< 到右侧车道线距离 */\n\
bool is_pressed_line   #/*!< Host车是否压到车道线上 */\n\
int32 pressed_lane_id  #/*!< Host车压到的车道ID */\n\
float64 current_speed  #/*!< 当前车速 */\n\
float64 longitude      #/*!< 高精地图坐标 x 经度 */\n\
float64 latitude       #/*!< 高精地图坐标 y 纬度 */\n\
float64 height         #/*!< 高精地图坐标 z 高程 */\n\
\n\
#/*!< 北东天坐标系 高精地图坐标到车身坐标的变换角*/\n\
float64 roll           #/*!< 参考INS/IMU输出,弧度单位,取值范围：(0 – 2π) */\n\
float64 pitch          #/*!< 参考INS/IMU输出,弧度单位, 取值范围：(0 – 2π)*/\n\
float64 yaw            #/*!< 参考INS/IMU输出,弧度单位,取值范围：(0 – 2π) */\n\
\n\
";
  }

  static const char* value(const ::perception_msgs::kouliang_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::kouliang_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.k_objects);
      stream.next(m.k_road_info);
      stream.next(m.k_vehicle_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kouliang_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::kouliang_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::kouliang_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "k_objects: ";
    s << std::endl;
    Printer< ::perception_msgs::objects_<ContainerAllocator> >::stream(s, indent + "  ", v.k_objects);
    s << indent << "k_road_info: ";
    s << std::endl;
    Printer< ::perception_msgs::road_info_<ContainerAllocator> >::stream(s, indent + "  ", v.k_road_info);
    s << indent << "k_vehicle_info: ";
    s << std::endl;
    Printer< ::perception_msgs::vehicle_info_<ContainerAllocator> >::stream(s, indent + "  ", v.k_vehicle_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_KOULIANG_H
