// Generated by gencpp from file perception_msgs/LaneMarkingColor.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_LANEMARKINGCOLOR_H
#define PERCEPTION_MSGS_MESSAGE_LANEMARKINGCOLOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct LaneMarkingColor_
{
  typedef LaneMarkingColor_<ContainerAllocator> Type;

  LaneMarkingColor_()
    {
    }
  LaneMarkingColor_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





  enum {
    COLOR_NONE = 0u,
    COLOR_YELLOW = 1u,
    COLOR_WHITE = 2u,
    COLOR_BLUE = 10u,
    COLOR_ORANGE = 11u,
  };


  typedef boost::shared_ptr< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> const> ConstPtr;

}; // struct LaneMarkingColor_

typedef ::perception_msgs::LaneMarkingColor_<std::allocator<void> > LaneMarkingColor;

typedef boost::shared_ptr< ::perception_msgs::LaneMarkingColor > LaneMarkingColorPtr;
typedef boost::shared_ptr< ::perception_msgs::LaneMarkingColor const> LaneMarkingColorConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::LaneMarkingColor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f49d6774ca727609125a79aab6896db3";
  }

  static const char* value(const ::perception_msgs::LaneMarkingColor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf49d6774ca727609ULL;
  static const uint64_t static_value2 = 0x125a79aab6896db3ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/LaneMarkingColor";
  }

  static const char* value(const ::perception_msgs::LaneMarkingColor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 COLOR_NONE = 0\n\
uint8 COLOR_YELLOW = 1\n\
uint8 COLOR_WHITE = 2\n\
uint8 COLOR_BLUE = 10\n\
uint8 COLOR_ORANGE = 11\n\
";
  }

  static const char* value(const ::perception_msgs::LaneMarkingColor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneMarkingColor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::LaneMarkingColor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::perception_msgs::LaneMarkingColor_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_LANEMARKINGCOLOR_H
