// Generated by gencpp from file perception_msgs/LaneMarkingType.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_LANEMARKINGTYPE_H
#define PERCEPTION_MSGS_MESSAGE_LANEMARKINGTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct LaneMarkingType_
{
  typedef LaneMarkingType_<ContainerAllocator> Type;

  LaneMarkingType_()
    {
    }
  LaneMarkingType_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





  enum {
    LBR_MARKING_NONE = 0u,
    LBR_MARKING_LONG_DASHED_LINE = 1u,
    LBR_MARKING_DOUBLE_SOLID_LINE = 2u,
    LBR_MARKING_SINGLE_SOLID_LINE = 3u,
    LBR_MARKING_RIGHT_SOLID_LINE_LEFT_DASHED_LINE = 4u,
    LBR_MARKING_LEFT_SOLID_LINE_RIGHT_DASHED_LINE = 5u,
    LBR_MARKING_DOUBLE_DASHED_LINE = 9u,
    LBR_MARKING_CURB = 11u,
    LBR_MARKING_GUARDRAIL = 17u,
    LBR_MARKING_UNKNOWN = 255u,
  };


  typedef boost::shared_ptr< ::perception_msgs::LaneMarkingType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::LaneMarkingType_<ContainerAllocator> const> ConstPtr;

}; // struct LaneMarkingType_

typedef ::perception_msgs::LaneMarkingType_<std::allocator<void> > LaneMarkingType;

typedef boost::shared_ptr< ::perception_msgs::LaneMarkingType > LaneMarkingTypePtr;
typedef boost::shared_ptr< ::perception_msgs::LaneMarkingType const> LaneMarkingTypeConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::LaneMarkingType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::LaneMarkingType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::LaneMarkingType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::LaneMarkingType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f91a7da9bcdab0e3f6da51ddfe6ddfb4";
  }

  static const char* value(const ::perception_msgs::LaneMarkingType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf91a7da9bcdab0e3ULL;
  static const uint64_t static_value2 = 0xf6da51ddfe6ddfb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/LaneMarkingType";
  }

  static const char* value(const ::perception_msgs::LaneMarkingType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LBR_MARKING_NONE = 0                                 # // 无\n\
uint8 LBR_MARKING_LONG_DASHED_LINE = 1                     # // 长虚线\n\
uint8 LBR_MARKING_DOUBLE_SOLID_LINE = 2                    # // 双实线\n\
uint8 LBR_MARKING_SINGLE_SOLID_LINE = 3                    # // 单实线\n\
uint8 LBR_MARKING_RIGHT_SOLID_LINE_LEFT_DASHED_LINE = 4    # // 左虚右实\n\
uint8 LBR_MARKING_LEFT_SOLID_LINE_RIGHT_DASHED_LINE = 5    # // 左实右虚\n\
uint8 LBR_MARKING_DOUBLE_DASHED_LINE = 9                   # // 双虚线\n\
uint8 LBR_MARKING_CURB = 11                                # // 路沿（道路边界）\n\
uint8 LBR_MARKING_GUARDRAIL = 17                           # // 护栏（道路边界）\n\
uint8 LBR_MARKING_UNKNOWN = 255                            # // 错误位\n\
";
  }

  static const char* value(const ::perception_msgs::LaneMarkingType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneMarkingType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::LaneMarkingType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::perception_msgs::LaneMarkingType_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_LANEMARKINGTYPE_H
