// Generated by gencpp from file perception_msgs/lane_info.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_LANE_INFO_H
#define PERCEPTION_MSGS_MESSAGE_LANE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct lane_info_
{
  typedef lane_info_<ContainerAllocator> Type;

  lane_info_()
    : header()
    , vleft_mark_index()
    , vright_mark_index()
    , speed_limit()
    , lane_id(0)
    , lane_hd_id(0)  {
    }
  lane_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vleft_mark_index(_alloc)
    , vright_mark_index(_alloc)
    , speed_limit(_alloc)
    , lane_id(0)
    , lane_hd_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _vleft_mark_index_type;
  _vleft_mark_index_type vleft_mark_index;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _vright_mark_index_type;
  _vright_mark_index_type vright_mark_index;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _speed_limit_type;
  _speed_limit_type speed_limit;

   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;

   typedef int32_t _lane_hd_id_type;
  _lane_hd_id_type lane_hd_id;





  typedef boost::shared_ptr< ::perception_msgs::lane_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::lane_info_<ContainerAllocator> const> ConstPtr;

}; // struct lane_info_

typedef ::perception_msgs::lane_info_<std::allocator<void> > lane_info;

typedef boost::shared_ptr< ::perception_msgs::lane_info > lane_infoPtr;
typedef boost::shared_ptr< ::perception_msgs::lane_info const> lane_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::lane_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::lane_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::lane_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::lane_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::lane_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::lane_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::lane_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::lane_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::lane_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca477e18b45a8a14cd2c571b94868ea9";
  }

  static const char* value(const ::perception_msgs::lane_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca477e18b45a8a14ULL;
  static const uint64_t static_value2 = 0xcd2c571b94868ea9ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::lane_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/lane_info";
  }

  static const char* value(const ::perception_msgs::lane_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::lane_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32[] vleft_mark_index\n\
uint32[] vright_mark_index\n\
float64[] speed_limit\n\
int32 lane_id                # /*< 车道线编号 当前车道是0，从左至右： - 2, -1, 0， 1, 2 */\n\
int32 lane_hd_id             # 高精地图对应的车道id \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::lane_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::lane_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vleft_mark_index);
      stream.next(m.vright_mark_index);
      stream.next(m.speed_limit);
      stream.next(m.lane_id);
      stream.next(m.lane_hd_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lane_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::lane_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::lane_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vleft_mark_index[]" << std::endl;
    for (size_t i = 0; i < v.vleft_mark_index.size(); ++i)
    {
      s << indent << "  vleft_mark_index[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.vleft_mark_index[i]);
    }
    s << indent << "vright_mark_index[]" << std::endl;
    for (size_t i = 0; i < v.vright_mark_index.size(); ++i)
    {
      s << indent << "  vright_mark_index[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.vright_mark_index[i]);
    }
    s << indent << "speed_limit[]" << std::endl;
    for (size_t i = 0; i < v.speed_limit.size(); ++i)
    {
      s << indent << "  speed_limit[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.speed_limit[i]);
    }
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "lane_hd_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_hd_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_LANE_INFO_H
