// Generated by gencpp from file perception_msgs/loc.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_LOC_H
#define PERCEPTION_MSGS_MESSAGE_LOC_H

#include <ros/service_traits.h>


#include <perception_msgs/locRequest.h>
#include <perception_msgs/locResponse.h>


namespace perception_msgs
{

struct loc
{

typedef locRequest Request;
typedef locResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct loc
} // namespace perception_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::perception_msgs::loc > {
  static const char* value()
  {
    return "0db8ee6345c259b3d2c65e91baa38658";
  }

  static const char* value(const ::perception_msgs::loc&) { return value(); }
};

template<>
struct DataType< ::perception_msgs::loc > {
  static const char* value()
  {
    return "perception_msgs/loc";
  }

  static const char* value(const ::perception_msgs::loc&) { return value(); }
};


// service_traits::MD5Sum< ::perception_msgs::locRequest> should match 
// service_traits::MD5Sum< ::perception_msgs::loc > 
template<>
struct MD5Sum< ::perception_msgs::locRequest>
{
  static const char* value()
  {
    return MD5Sum< ::perception_msgs::loc >::value();
  }
  static const char* value(const ::perception_msgs::locRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_msgs::locRequest> should match 
// service_traits::DataType< ::perception_msgs::loc > 
template<>
struct DataType< ::perception_msgs::locRequest>
{
  static const char* value()
  {
    return DataType< ::perception_msgs::loc >::value();
  }
  static const char* value(const ::perception_msgs::locRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::perception_msgs::locResponse> should match 
// service_traits::MD5Sum< ::perception_msgs::loc > 
template<>
struct MD5Sum< ::perception_msgs::locResponse>
{
  static const char* value()
  {
    return MD5Sum< ::perception_msgs::loc >::value();
  }
  static const char* value(const ::perception_msgs::locResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_msgs::locResponse> should match 
// service_traits::DataType< ::perception_msgs::loc > 
template<>
struct DataType< ::perception_msgs::locResponse>
{
  static const char* value()
  {
    return DataType< ::perception_msgs::loc >::value();
  }
  static const char* value(const ::perception_msgs::locResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_LOC_H
