// Generated by gencpp from file perception_msgs/objects_debug.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_OBJECTS_DEBUG_H
#define PERCEPTION_MSGS_MESSAGE_OBJECTS_DEBUG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct objects_debug_
{
  typedef objects_debug_<ContainerAllocator> Type;

  objects_debug_()
    : header()
    , radarseq(0)
    , visionseq(0)
    , speedseq(0)  {
    }
  objects_debug_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radarseq(0)
    , visionseq(0)
    , speedseq(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _radarseq_type;
  _radarseq_type radarseq;

   typedef int32_t _visionseq_type;
  _visionseq_type visionseq;

   typedef int32_t _speedseq_type;
  _speedseq_type speedseq;





  typedef boost::shared_ptr< ::perception_msgs::objects_debug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::objects_debug_<ContainerAllocator> const> ConstPtr;

}; // struct objects_debug_

typedef ::perception_msgs::objects_debug_<std::allocator<void> > objects_debug;

typedef boost::shared_ptr< ::perception_msgs::objects_debug > objects_debugPtr;
typedef boost::shared_ptr< ::perception_msgs::objects_debug const> objects_debugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::objects_debug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::objects_debug_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::objects_debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::objects_debug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::objects_debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::objects_debug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::objects_debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::objects_debug_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::objects_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30998d36ca1186daed508963cde43296";
  }

  static const char* value(const ::perception_msgs::objects_debug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30998d36ca1186daULL;
  static const uint64_t static_value2 = 0xed508963cde43296ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::objects_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/objects_debug";
  }

  static const char* value(const ::perception_msgs::objects_debug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::objects_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 radarseq\n\
int32 visionseq\n\
int32 speedseq\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::objects_debug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::objects_debug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radarseq);
      stream.next(m.visionseq);
      stream.next(m.speedseq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objects_debug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::objects_debug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::objects_debug_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radarseq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.radarseq);
    s << indent << "visionseq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.visionseq);
    s << indent << "speedseq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speedseq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_OBJECTS_DEBUG_H
