// Generated by gencpp from file perception_msgs/odom.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_ODOM_H
#define PERCEPTION_MSGS_MESSAGE_ODOM_H

#include <ros/service_traits.h>


#include <perception_msgs/odomRequest.h>
#include <perception_msgs/odomResponse.h>


namespace perception_msgs
{

struct odom
{

typedef odomRequest Request;
typedef odomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct odom
} // namespace perception_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::perception_msgs::odom > {
  static const char* value()
  {
    return "a40844a8045a49855114bdf51eaac318";
  }

  static const char* value(const ::perception_msgs::odom&) { return value(); }
};

template<>
struct DataType< ::perception_msgs::odom > {
  static const char* value()
  {
    return "perception_msgs/odom";
  }

  static const char* value(const ::perception_msgs::odom&) { return value(); }
};


// service_traits::MD5Sum< ::perception_msgs::odomRequest> should match 
// service_traits::MD5Sum< ::perception_msgs::odom > 
template<>
struct MD5Sum< ::perception_msgs::odomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::perception_msgs::odom >::value();
  }
  static const char* value(const ::perception_msgs::odomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_msgs::odomRequest> should match 
// service_traits::DataType< ::perception_msgs::odom > 
template<>
struct DataType< ::perception_msgs::odomRequest>
{
  static const char* value()
  {
    return DataType< ::perception_msgs::odom >::value();
  }
  static const char* value(const ::perception_msgs::odomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::perception_msgs::odomResponse> should match 
// service_traits::MD5Sum< ::perception_msgs::odom > 
template<>
struct MD5Sum< ::perception_msgs::odomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::perception_msgs::odom >::value();
  }
  static const char* value(const ::perception_msgs::odomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_msgs::odomResponse> should match 
// service_traits::DataType< ::perception_msgs::odom > 
template<>
struct DataType< ::perception_msgs::odomResponse>
{
  static const char* value()
  {
    return DataType< ::perception_msgs::odom >::value();
  }
  static const char* value(const ::perception_msgs::odomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_ODOM_H
