// Generated by gencpp from file perception_msgs/radar_curb.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_RADAR_CURB_H
#define PERCEPTION_MSGS_MESSAGE_RADAR_CURB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct radar_curb_
{
  typedef radar_curb_<ContainerAllocator> Type;

  radar_curb_()
    : header()
    , timestamp(0)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , x_start(0.0)
    , x_end(0.0)
    , prob(0.0)  {
    }
  radar_curb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , x_start(0.0)
    , x_end(0.0)
    , prob(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;

   typedef double _x_start_type;
  _x_start_type x_start;

   typedef double _x_end_type;
  _x_end_type x_end;

   typedef double _prob_type;
  _prob_type prob;





  typedef boost::shared_ptr< ::perception_msgs::radar_curb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::radar_curb_<ContainerAllocator> const> ConstPtr;

}; // struct radar_curb_

typedef ::perception_msgs::radar_curb_<std::allocator<void> > radar_curb;

typedef boost::shared_ptr< ::perception_msgs::radar_curb > radar_curbPtr;
typedef boost::shared_ptr< ::perception_msgs::radar_curb const> radar_curbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::radar_curb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::radar_curb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::radar_curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff260e5d1bdb20a5953cfbd279b3cfa6";
  }

  static const char* value(const ::perception_msgs::radar_curb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff260e5d1bdb20a5ULL;
  static const uint64_t static_value2 = 0x953cfbd279b3cfa6ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::radar_curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/radar_curb";
  }

  static const char* value(const ::perception_msgs::radar_curb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::radar_curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 timestamp\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
float64 x_start\n\
float64 x_end\n\
float64 prob\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::radar_curb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::radar_curb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.x_start);
      stream.next(m.x_end);
      stream.next(m.prob);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_curb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::radar_curb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::radar_curb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    s << indent << "x_start: ";
    Printer<double>::stream(s, indent + "  ", v.x_start);
    s << indent << "x_end: ";
    Printer<double>::stream(s, indent + "  ", v.x_end);
    s << indent << "prob: ";
    Printer<double>::stream(s, indent + "  ", v.prob);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_RADAR_CURB_H
