// Generated by gencpp from file perception_msgs/radar_curbs.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_RADAR_CURBS_H
#define PERCEPTION_MSGS_MESSAGE_RADAR_CURBS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_msgs/radar_curb.h>
#include <perception_msgs/radar_curbpt.h>
#include <perception_msgs/radar_curbpt.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct radar_curbs_
{
  typedef radar_curbs_<ContainerAllocator> Type;

  radar_curbs_()
    : header()
    , timestamp(0)
    , curb_counts(0)
    , radar_curbs()
    , left_curb_pts()
    , right_curb_pts()  {
    }
  radar_curbs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , curb_counts(0)
    , radar_curbs(_alloc)
    , left_curb_pts(_alloc)
    , right_curb_pts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _curb_counts_type;
  _curb_counts_type curb_counts;

   typedef std::vector< ::perception_msgs::radar_curb_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::radar_curb_<ContainerAllocator> >::other >  _radar_curbs_type;
  _radar_curbs_type radar_curbs;

   typedef std::vector< ::perception_msgs::radar_curbpt_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::radar_curbpt_<ContainerAllocator> >::other >  _left_curb_pts_type;
  _left_curb_pts_type left_curb_pts;

   typedef std::vector< ::perception_msgs::radar_curbpt_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::radar_curbpt_<ContainerAllocator> >::other >  _right_curb_pts_type;
  _right_curb_pts_type right_curb_pts;





  typedef boost::shared_ptr< ::perception_msgs::radar_curbs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::radar_curbs_<ContainerAllocator> const> ConstPtr;

}; // struct radar_curbs_

typedef ::perception_msgs::radar_curbs_<std::allocator<void> > radar_curbs;

typedef boost::shared_ptr< ::perception_msgs::radar_curbs > radar_curbsPtr;
typedef boost::shared_ptr< ::perception_msgs::radar_curbs const> radar_curbsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::radar_curbs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::radar_curbs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curbs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curbs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curbs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curbs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curbs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curbs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::radar_curbs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dbdd3f290ade87a74cc73e8a44e3ad5";
  }

  static const char* value(const ::perception_msgs::radar_curbs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dbdd3f290ade87aULL;
  static const uint64_t static_value2 = 0x74cc73e8a44e3ad5ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::radar_curbs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/radar_curbs";
  }

  static const char* value(const ::perception_msgs::radar_curbs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::radar_curbs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 timestamp\n\
uint32 curb_counts\n\
radar_curb[] radar_curbs\n\
radar_curbpt[] left_curb_pts\n\
radar_curbpt[] right_curb_pts\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: perception_msgs/radar_curb\n\
Header header\n\
uint64 timestamp\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
float64 x_start\n\
float64 x_end\n\
float64 prob\n\
\n\
================================================================================\n\
MSG: perception_msgs/radar_curbpt\n\
Header header\n\
uint64 timestamp\n\
float64 x\n\
float64 y\n\
float64 vx\n\
float64 vy\n\
float64 rcs\n\
";
  }

  static const char* value(const ::perception_msgs::radar_curbs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::radar_curbs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.curb_counts);
      stream.next(m.radar_curbs);
      stream.next(m.left_curb_pts);
      stream.next(m.right_curb_pts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_curbs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::radar_curbs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::radar_curbs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "curb_counts: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.curb_counts);
    s << indent << "radar_curbs[]" << std::endl;
    for (size_t i = 0; i < v.radar_curbs.size(); ++i)
    {
      s << indent << "  radar_curbs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::radar_curb_<ContainerAllocator> >::stream(s, indent + "    ", v.radar_curbs[i]);
    }
    s << indent << "left_curb_pts[]" << std::endl;
    for (size_t i = 0; i < v.left_curb_pts.size(); ++i)
    {
      s << indent << "  left_curb_pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::radar_curbpt_<ContainerAllocator> >::stream(s, indent + "    ", v.left_curb_pts[i]);
    }
    s << indent << "right_curb_pts[]" << std::endl;
    for (size_t i = 0; i < v.right_curb_pts.size(); ++i)
    {
      s << indent << "  right_curb_pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::radar_curbpt_<ContainerAllocator> >::stream(s, indent + "    ", v.right_curb_pts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_RADAR_CURBS_H
