// Generated by gencpp from file perception_msgs/radar_objects.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_RADAR_OBJECTS_H
#define PERCEPTION_MSGS_MESSAGE_RADAR_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_msgs/radar_object.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct radar_objects_
{
  typedef radar_objects_<ContainerAllocator> Type;

  radar_objects_()
    : header()
    , timestamp(0)
    , radar_counts(0)
    , radar_objects()  {
    }
  radar_objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , radar_counts(0)
    , radar_objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _radar_counts_type;
  _radar_counts_type radar_counts;

   typedef std::vector< ::perception_msgs::radar_object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::radar_object_<ContainerAllocator> >::other >  _radar_objects_type;
  _radar_objects_type radar_objects;





  typedef boost::shared_ptr< ::perception_msgs::radar_objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::radar_objects_<ContainerAllocator> const> ConstPtr;

}; // struct radar_objects_

typedef ::perception_msgs::radar_objects_<std::allocator<void> > radar_objects;

typedef boost::shared_ptr< ::perception_msgs::radar_objects > radar_objectsPtr;
typedef boost::shared_ptr< ::perception_msgs::radar_objects const> radar_objectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::radar_objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::radar_objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::radar_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b7d6df6f9aef2a562407cea3f4b58b4";
  }

  static const char* value(const ::perception_msgs::radar_objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b7d6df6f9aef2a5ULL;
  static const uint64_t static_value2 = 0x62407cea3f4b58b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::radar_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/radar_objects";
  }

  static const char* value(const ::perception_msgs::radar_objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::radar_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 timestamp\n\
uint32 radar_counts\n\
radar_object[] radar_objects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: perception_msgs/radar_object\n\
Header header\n\
uint64 timestamp    # unit: us\n\
uint32 group_id     # radar id (front: 0; left front: 1; right front: 2)\n\
uint32 track_id\n\
uint32 track_status\n\
uint32 obj_type\n\
coord3d coordinate\n\
coord3d velocity\n\
coord3d acceleration\n\
coord3d size_of_box\n\
float64 rcs\n\
uint32 background_level\n\
float64 prob\n\
track_flag track_flag\n\
\n\
================================================================================\n\
MSG: perception_msgs/coord3d\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: perception_msgs/track_flag\n\
Header header\n\
int32 find_times\n\
int32 wrong_times\n\
int32 lost_times\n\
int32 threshold_find\n\
int32 threshold_wrong\n\
int32 threshold_lost\n\
";
  }

  static const char* value(const ::perception_msgs::radar_objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::radar_objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.radar_counts);
      stream.next(m.radar_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::radar_objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::radar_objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "radar_counts: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radar_counts);
    s << indent << "radar_objects[]" << std::endl;
    for (size_t i = 0; i < v.radar_objects.size(); ++i)
    {
      s << indent << "  radar_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::radar_object_<ContainerAllocator> >::stream(s, indent + "    ", v.radar_objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_RADAR_OBJECTS_H
