// Generated by gencpp from file perception_msgs/radar_curbpt.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_RADAR_CURBPT_H
#define PERCEPTION_MSGS_MESSAGE_RADAR_CURBPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct radar_curbpt_
{
  typedef radar_curbpt_<ContainerAllocator> Type;

  radar_curbpt_()
    : header()
    , timestamp(0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , rcs(0.0)  {
    }
  radar_curbpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , rcs(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _rcs_type;
  _rcs_type rcs;





  typedef boost::shared_ptr< ::perception_msgs::radar_curbpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::radar_curbpt_<ContainerAllocator> const> ConstPtr;

}; // struct radar_curbpt_

typedef ::perception_msgs::radar_curbpt_<std::allocator<void> > radar_curbpt;

typedef boost::shared_ptr< ::perception_msgs::radar_curbpt > radar_curbptPtr;
typedef boost::shared_ptr< ::perception_msgs::radar_curbpt const> radar_curbptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::radar_curbpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::radar_curbpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::radar_curbpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::radar_curbpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::radar_curbpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2935929a53a79aee16384e8cfb0c9d41";
  }

  static const char* value(const ::perception_msgs::radar_curbpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2935929a53a79aeeULL;
  static const uint64_t static_value2 = 0x16384e8cfb0c9d41ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/radar_curbpt";
  }

  static const char* value(const ::perception_msgs::radar_curbpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 timestamp\n\
float64 x\n\
float64 y\n\
float64 vx\n\
float64 vy\n\
float64 rcs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::radar_curbpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.rcs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_curbpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::radar_curbpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::radar_curbpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "rcs: ";
    Printer<double>::stream(s, indent + "  ", v.rcs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_RADAR_CURBPT_H
