// Generated by gencpp from file perception_msgs/road_info.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_ROAD_INFO_H
#define PERCEPTION_MSGS_MESSAGE_ROAD_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_msgs/lane_info.h>
#include <perception_msgs/lane_mark_info.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct road_info_
{
  typedef road_info_<ContainerAllocator> Type;

  road_info_()
    : header()
    , sys_time_us(0)
    , vlanes()
    , vlane_marks()
    , lane_departure_angle(0.0)
    , lane_departure_distance(0.0)  {
    }
  road_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sys_time_us(0)
    , vlanes(_alloc)
    , vlane_marks(_alloc)
    , lane_departure_angle(0.0)
    , lane_departure_distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _sys_time_us_type;
  _sys_time_us_type sys_time_us;

   typedef std::vector< ::perception_msgs::lane_info_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::lane_info_<ContainerAllocator> >::other >  _vlanes_type;
  _vlanes_type vlanes;

   typedef std::vector< ::perception_msgs::lane_mark_info_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::lane_mark_info_<ContainerAllocator> >::other >  _vlane_marks_type;
  _vlane_marks_type vlane_marks;

   typedef double _lane_departure_angle_type;
  _lane_departure_angle_type lane_departure_angle;

   typedef double _lane_departure_distance_type;
  _lane_departure_distance_type lane_departure_distance;





  typedef boost::shared_ptr< ::perception_msgs::road_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::road_info_<ContainerAllocator> const> ConstPtr;

}; // struct road_info_

typedef ::perception_msgs::road_info_<std::allocator<void> > road_info;

typedef boost::shared_ptr< ::perception_msgs::road_info > road_infoPtr;
typedef boost::shared_ptr< ::perception_msgs::road_info const> road_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::road_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::road_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::road_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::road_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::road_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::road_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::road_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::road_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::road_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb37f5b751bb1fb7d1efe50074f417de";
  }

  static const char* value(const ::perception_msgs::road_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb37f5b751bb1fb7ULL;
  static const uint64_t static_value2 = 0xd1efe50074f417deULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::road_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/road_info";
  }

  static const char* value(const ::perception_msgs::road_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::road_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 sys_time_us              #/*用于各传感器消息时间同步的时间戳*/\n\
lane_info[] vlanes              #/*存储车道信息*/\n\
lane_mark_info[] vlane_marks    #/*存储车道线信息*/\n\
float64 lane_departure_angle     #/*!< 道路与车身坐标系的夹角(弧度单位[-PI,PI]) */\n\
float64 lane_departure_distance  # /*!< 自车与车道中心线的距离 */\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: perception_msgs/lane_info\n\
Header header\n\
uint32[] vleft_mark_index\n\
uint32[] vright_mark_index\n\
float64[] speed_limit\n\
int32 lane_id                # /*< 车道线编号 当前车道是0，从左至右： - 2, -1, 0， 1, 2 */\n\
int32 lane_hd_id             # 高精地图对应的车道id \n\
\n\
================================================================================\n\
MSG: perception_msgs/lane_mark_info\n\
Header header\n\
uint8 mark_type      #/*!< 类型 LaneMarkingType*/\n\
uint8 mark_color     #/*!< 类型 LaneMarkingColor */\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d            # /* y = a * pow(x,3) + b * pow(x,2) + c * x + d */\n\
float64 x_start      # /*!< 纵向起始点(米) */\n\
float64 x_end        # /*!< 纵向终止点(米) */\n\
\n\
float64 image_a\n\
float64 image_b\n\
float64 image_c\n\
float64 image_d\n\
float64 image_x_start\n\
float64 image_x_end\n\
";
  }

  static const char* value(const ::perception_msgs::road_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::road_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sys_time_us);
      stream.next(m.vlanes);
      stream.next(m.vlane_marks);
      stream.next(m.lane_departure_angle);
      stream.next(m.lane_departure_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct road_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::road_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::road_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sys_time_us: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sys_time_us);
    s << indent << "vlanes[]" << std::endl;
    for (size_t i = 0; i < v.vlanes.size(); ++i)
    {
      s << indent << "  vlanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::lane_info_<ContainerAllocator> >::stream(s, indent + "    ", v.vlanes[i]);
    }
    s << indent << "vlane_marks[]" << std::endl;
    for (size_t i = 0; i < v.vlane_marks.size(); ++i)
    {
      s << indent << "  vlane_marks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::lane_mark_info_<ContainerAllocator> >::stream(s, indent + "    ", v.vlane_marks[i]);
    }
    s << indent << "lane_departure_angle: ";
    Printer<double>::stream(s, indent + "  ", v.lane_departure_angle);
    s << indent << "lane_departure_distance: ";
    Printer<double>::stream(s, indent + "  ", v.lane_departure_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_ROAD_INFO_H
