// Generated by gencpp from file perception_msgs/routplan_inner_monitor.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_ROUTPLAN_INNER_MONITOR_H
#define PERCEPTION_MSGS_MESSAGE_ROUTPLAN_INNER_MONITOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct routplan_inner_monitor_
{
  typedef routplan_inner_monitor_<ContainerAllocator> Type;

  routplan_inner_monitor_()
    : header()
    , inner_variable()  {
    }
  routplan_inner_monitor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , inner_variable(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _inner_variable_type;
  _inner_variable_type inner_variable;





  typedef boost::shared_ptr< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> const> ConstPtr;

}; // struct routplan_inner_monitor_

typedef ::perception_msgs::routplan_inner_monitor_<std::allocator<void> > routplan_inner_monitor;

typedef boost::shared_ptr< ::perception_msgs::routplan_inner_monitor > routplan_inner_monitorPtr;
typedef boost::shared_ptr< ::perception_msgs::routplan_inner_monitor const> routplan_inner_monitorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e57052606733b6f318617964f5650a1c";
  }

  static const char* value(const ::perception_msgs::routplan_inner_monitor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe57052606733b6f3ULL;
  static const uint64_t static_value2 = 0x18617964f5650a1cULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/routplan_inner_monitor";
  }

  static const char* value(const ::perception_msgs::routplan_inner_monitor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# time information\n\
Header header\n\
\n\
float64[] inner_variable #1.Yaw_Lane2car_Rad;2.Disp_Lane2Car_m;3.I_biase_control;4,I_control;\n\
			#5,LaneCurve_control; 6,LaneKeep_control;7,PTP_WhlAngStp_Deg;\n\
			#8,PTP_VxStp_ms;9,PTP_AxStpAcc_ms2;10,PTP_AxStpDec_ms2;11,PTP_VxStp_msb\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::routplan_inner_monitor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.inner_variable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct routplan_inner_monitor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::routplan_inner_monitor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::routplan_inner_monitor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "inner_variable[]" << std::endl;
    for (size_t i = 0; i < v.inner_variable.size(); ++i)
    {
      s << indent << "  inner_variable[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.inner_variable[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_ROUTPLAN_INNER_MONITOR_H
