// Generated by gencpp from file perception_msgs/steering_info.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_STEERING_INFO_H
#define PERCEPTION_MSGS_MESSAGE_STEERING_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct steering_info_
{
  typedef steering_info_<ContainerAllocator> Type;

  steering_info_()
    : header()
    , sys_time_us(0)
    , clock_wise(false)
    , steer_angle_isvalid(false)
    , steer_angle_speed_isvalid(false)
    , steer_angle(0.0)
    , steer_angle_speed(0.0)
    , steer_torque(0.0)  {
    }
  steering_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sys_time_us(0)
    , clock_wise(false)
    , steer_angle_isvalid(false)
    , steer_angle_speed_isvalid(false)
    , steer_angle(0.0)
    , steer_angle_speed(0.0)
    , steer_torque(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _sys_time_us_type;
  _sys_time_us_type sys_time_us;

   typedef uint8_t _clock_wise_type;
  _clock_wise_type clock_wise;

   typedef uint8_t _steer_angle_isvalid_type;
  _steer_angle_isvalid_type steer_angle_isvalid;

   typedef uint8_t _steer_angle_speed_isvalid_type;
  _steer_angle_speed_isvalid_type steer_angle_speed_isvalid;

   typedef double _steer_angle_type;
  _steer_angle_type steer_angle;

   typedef double _steer_angle_speed_type;
  _steer_angle_speed_type steer_angle_speed;

   typedef double _steer_torque_type;
  _steer_torque_type steer_torque;





  typedef boost::shared_ptr< ::perception_msgs::steering_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::steering_info_<ContainerAllocator> const> ConstPtr;

}; // struct steering_info_

typedef ::perception_msgs::steering_info_<std::allocator<void> > steering_info;

typedef boost::shared_ptr< ::perception_msgs::steering_info > steering_infoPtr;
typedef boost::shared_ptr< ::perception_msgs::steering_info const> steering_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::steering_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::steering_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::steering_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::steering_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::steering_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::steering_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::steering_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::steering_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::steering_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58e3be8b7e8cb4337b12d785eb5ca67e";
  }

  static const char* value(const ::perception_msgs::steering_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58e3be8b7e8cb433ULL;
  static const uint64_t static_value2 = 0x7b12d785eb5ca67eULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::steering_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/steering_info";
  }

  static const char* value(const ::perception_msgs::steering_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::steering_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 sys_time_us              #/*用于各传感器消息时间同步的时间戳*/\n\
bool clock_wise\n\
bool steer_angle_isvalid\n\
bool steer_angle_speed_isvalid\n\
float64 steer_angle\n\
float64 steer_angle_speed\n\
float64 steer_torque\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::steering_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::steering_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sys_time_us);
      stream.next(m.clock_wise);
      stream.next(m.steer_angle_isvalid);
      stream.next(m.steer_angle_speed_isvalid);
      stream.next(m.steer_angle);
      stream.next(m.steer_angle_speed);
      stream.next(m.steer_torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct steering_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::steering_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::steering_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sys_time_us: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sys_time_us);
    s << indent << "clock_wise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clock_wise);
    s << indent << "steer_angle_isvalid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.steer_angle_isvalid);
    s << indent << "steer_angle_speed_isvalid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.steer_angle_speed_isvalid);
    s << indent << "steer_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steer_angle);
    s << indent << "steer_angle_speed: ";
    Printer<double>::stream(s, indent + "  ", v.steer_angle_speed);
    s << indent << "steer_torque: ";
    Printer<double>::stream(s, indent + "  ", v.steer_torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_STEERING_INFO_H
