// Generated by gencpp from file perception_msgs/track_flag.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_TRACK_FLAG_H
#define PERCEPTION_MSGS_MESSAGE_TRACK_FLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct track_flag_
{
  typedef track_flag_<ContainerAllocator> Type;

  track_flag_()
    : header()
    , find_times(0)
    , wrong_times(0)
    , lost_times(0)
    , threshold_find(0)
    , threshold_wrong(0)
    , threshold_lost(0)  {
    }
  track_flag_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , find_times(0)
    , wrong_times(0)
    , lost_times(0)
    , threshold_find(0)
    , threshold_wrong(0)
    , threshold_lost(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _find_times_type;
  _find_times_type find_times;

   typedef int32_t _wrong_times_type;
  _wrong_times_type wrong_times;

   typedef int32_t _lost_times_type;
  _lost_times_type lost_times;

   typedef int32_t _threshold_find_type;
  _threshold_find_type threshold_find;

   typedef int32_t _threshold_wrong_type;
  _threshold_wrong_type threshold_wrong;

   typedef int32_t _threshold_lost_type;
  _threshold_lost_type threshold_lost;





  typedef boost::shared_ptr< ::perception_msgs::track_flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::track_flag_<ContainerAllocator> const> ConstPtr;

}; // struct track_flag_

typedef ::perception_msgs::track_flag_<std::allocator<void> > track_flag;

typedef boost::shared_ptr< ::perception_msgs::track_flag > track_flagPtr;
typedef boost::shared_ptr< ::perception_msgs::track_flag const> track_flagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::track_flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::track_flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::track_flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::track_flag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::track_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::track_flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::track_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::track_flag_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::track_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9874a4368746757e32641fd404a993a4";
  }

  static const char* value(const ::perception_msgs::track_flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9874a4368746757eULL;
  static const uint64_t static_value2 = 0x32641fd404a993a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::track_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/track_flag";
  }

  static const char* value(const ::perception_msgs::track_flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::track_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 find_times\n\
int32 wrong_times\n\
int32 lost_times\n\
int32 threshold_find\n\
int32 threshold_wrong\n\
int32 threshold_lost\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::track_flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::track_flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.find_times);
      stream.next(m.wrong_times);
      stream.next(m.lost_times);
      stream.next(m.threshold_find);
      stream.next(m.threshold_wrong);
      stream.next(m.threshold_lost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct track_flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::track_flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::track_flag_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "find_times: ";
    Printer<int32_t>::stream(s, indent + "  ", v.find_times);
    s << indent << "wrong_times: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrong_times);
    s << indent << "lost_times: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lost_times);
    s << indent << "threshold_find: ";
    Printer<int32_t>::stream(s, indent + "  ", v.threshold_find);
    s << indent << "threshold_wrong: ";
    Printer<int32_t>::stream(s, indent + "  ", v.threshold_wrong);
    s << indent << "threshold_lost: ";
    Printer<int32_t>::stream(s, indent + "  ", v.threshold_lost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_TRACK_FLAG_H
