// Generated by gencpp from file perception_msgs/turnlight.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_TURNLIGHT_H
#define PERCEPTION_MSGS_MESSAGE_TURNLIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_msgs
{
template <class ContainerAllocator>
struct turnlight_
{
  typedef turnlight_<ContainerAllocator> Type;

  turnlight_()
    : left_turnlight_status(false)
    , right_turnlight_status(false)  {
    }
  turnlight_(const ContainerAllocator& _alloc)
    : left_turnlight_status(false)
    , right_turnlight_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _left_turnlight_status_type;
  _left_turnlight_status_type left_turnlight_status;

   typedef uint8_t _right_turnlight_status_type;
  _right_turnlight_status_type right_turnlight_status;





  typedef boost::shared_ptr< ::perception_msgs::turnlight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::turnlight_<ContainerAllocator> const> ConstPtr;

}; // struct turnlight_

typedef ::perception_msgs::turnlight_<std::allocator<void> > turnlight;

typedef boost::shared_ptr< ::perception_msgs::turnlight > turnlightPtr;
typedef boost::shared_ptr< ::perception_msgs::turnlight const> turnlightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::turnlight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::turnlight_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::turnlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::turnlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::turnlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::turnlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::turnlight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::turnlight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::turnlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79469178fa3c7fd943e7cd77ca419db1";
  }

  static const char* value(const ::perception_msgs::turnlight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79469178fa3c7fd9ULL;
  static const uint64_t static_value2 = 0x43e7cd77ca419db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::turnlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/turnlight";
  }

  static const char* value(const ::perception_msgs::turnlight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::turnlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left_turnlight_status    #// true, turn on;\n\
bool right_turnlight_status \n\
";
  }

  static const char* value(const ::perception_msgs::turnlight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::turnlight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_turnlight_status);
      stream.next(m.right_turnlight_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turnlight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::turnlight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::turnlight_<ContainerAllocator>& v)
  {
    s << indent << "left_turnlight_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_turnlight_status);
    s << indent << "right_turnlight_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_turnlight_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_TURNLIGHT_H
