// Generated by gencpp from file perception_msgs/vehicle_speed.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_VEHICLE_SPEED_H
#define PERCEPTION_MSGS_MESSAGE_VEHICLE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct vehicle_speed_
{
  typedef vehicle_speed_<ContainerAllocator> Type;

  vehicle_speed_()
    : header()
    , sys_time_us(0)
    , vehicle_speed_isvalid(false)
    , vehicle_speed(0.0)  {
    }
  vehicle_speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sys_time_us(0)
    , vehicle_speed_isvalid(false)
    , vehicle_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _sys_time_us_type;
  _sys_time_us_type sys_time_us;

   typedef uint8_t _vehicle_speed_isvalid_type;
  _vehicle_speed_isvalid_type vehicle_speed_isvalid;

   typedef double _vehicle_speed_type;
  _vehicle_speed_type vehicle_speed;





  typedef boost::shared_ptr< ::perception_msgs::vehicle_speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::vehicle_speed_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_speed_

typedef ::perception_msgs::vehicle_speed_<std::allocator<void> > vehicle_speed;

typedef boost::shared_ptr< ::perception_msgs::vehicle_speed > vehicle_speedPtr;
typedef boost::shared_ptr< ::perception_msgs::vehicle_speed const> vehicle_speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::vehicle_speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::vehicle_speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::vehicle_speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::vehicle_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::vehicle_speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9940f18621d349d13f4d84f44925c30b";
  }

  static const char* value(const ::perception_msgs::vehicle_speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9940f18621d349d1ULL;
  static const uint64_t static_value2 = 0x3f4d84f44925c30bULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/vehicle_speed";
  }

  static const char* value(const ::perception_msgs::vehicle_speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 sys_time_us              #/*用于各传感器消息时间同步的时间戳*/\n\
bool vehicle_speed_isvalid\n\
float64 vehicle_speed\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::vehicle_speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sys_time_us);
      stream.next(m.vehicle_speed_isvalid);
      stream.next(m.vehicle_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::vehicle_speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::vehicle_speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sys_time_us: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sys_time_us);
    s << indent << "vehicle_speed_isvalid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle_speed_isvalid);
    s << indent << "vehicle_speed: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_VEHICLE_SPEED_H
