// Generated by gencpp from file perception_msgs/vehicle_imu.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_VEHICLE_IMU_H
#define PERCEPTION_MSGS_MESSAGE_VEHICLE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct vehicle_imu_
{
  typedef vehicle_imu_<ContainerAllocator> Type;

  vehicle_imu_()
    : header()
    , px2_time(0.0)
    , x_acc(0.0)
    , y_acc(0.0)
    , z_acc(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , yaw_rate(0.0)  {
    }
  vehicle_imu_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , px2_time(0.0)
    , x_acc(0.0)
    , y_acc(0.0)
    , z_acc(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_rate(0.0)
    , pitch_rate(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _px2_time_type;
  _px2_time_type px2_time;

   typedef double _x_acc_type;
  _x_acc_type x_acc;

   typedef double _y_acc_type;
  _y_acc_type y_acc;

   typedef double _z_acc_type;
  _z_acc_type z_acc;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef double _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::perception_msgs::vehicle_imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::vehicle_imu_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_imu_

typedef ::perception_msgs::vehicle_imu_<std::allocator<void> > vehicle_imu;

typedef boost::shared_ptr< ::perception_msgs::vehicle_imu > vehicle_imuPtr;
typedef boost::shared_ptr< ::perception_msgs::vehicle_imu const> vehicle_imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::vehicle_imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::vehicle_imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/shawn/baidu/ai-auto/l3-apollo/catkin_build/src/modules/ros_msgs/perception/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::vehicle_imu_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::vehicle_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::vehicle_imu_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eab403552a753f6cc9e4e90ced71dc93";
  }

  static const char* value(const ::perception_msgs::vehicle_imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeab403552a753f6cULL;
  static const uint64_t static_value2 = 0xc9e4e90ced71dc93ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/vehicle_imu";
  }

  static const char* value(const ::perception_msgs::vehicle_imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header           # ros time\n\
float64 px2_time        # px2_time\n\
float64 x_acc           \n\
float64 y_acc\n\
float64 z_acc\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
float64 roll_rate\n\
float64 pitch_rate\n\
float64 yaw_rate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::vehicle_imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.px2_time);
      stream.next(m.x_acc);
      stream.next(m.y_acc);
      stream.next(m.z_acc);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.roll_rate);
      stream.next(m.pitch_rate);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::vehicle_imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::vehicle_imu_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "px2_time: ";
    Printer<double>::stream(s, indent + "  ", v.px2_time);
    s << indent << "x_acc: ";
    Printer<double>::stream(s, indent + "  ", v.x_acc);
    s << indent << "y_acc: ";
    Printer<double>::stream(s, indent + "  ", v.y_acc);
    s << indent << "z_acc: ";
    Printer<double>::stream(s, indent + "  ", v.z_acc);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll_rate: ";
    Printer<double>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "pitch_rate: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_VEHICLE_IMU_H
